### ISSUE TITLE
Errores en los enlaces en el README

### ISSUE THREAD

**Issue by llrs** [civio/scraper-pge#3]
¡¡Muchas gracias por hacer este trabajo!!

Los links (al ministerio:
http://www.sepg.pap.minhap.gob.es/sitios/sepg/es-ES/Presupuestos/pge2014/Paginas/pge2014.aspx
y al libro azul:
 http://www.sepg.pap.minhap.gob.es/sitios/sepg/es-ES/Presupuestos/pge2014/Documents/LIBROAZUL2014.pdf) en el README para entender los presupuestos redireccionan a una página de error de redirección. 

Parece ser que el enlace del libro azul de este año es:
http://www.sepg.pap.hacienda.gob.es/sitios/sepg/es-ES/Presupuestos/ProyectoPGE2019/Documents/LIBRO%20AZUL%202019%20(con%20marcadores).pdf

Aprovecho para preguntar si la P de las carpetas del output tiene algún significado (Proyecto?) y si fuera así si los que no tienen P son los validados al final del ejercicio o no. 

¡¡Muchas gracias!!

**Comment by mcalero** [comment]
dirección equivocada.

**Comment by dcabo** [comment]
Hola, gracias por avisar: en el Ministerio han cambiado varias veces la estructura de la página y nunca respetan los enlaces viejos.

He enlazado ahora al Libro Azul de 2018, porque si apunto al proyecto de 2019 se romperá el enlace de nuevo en cuanto lo aprueben. No cambia (casi) nada de año a año y con suerte no lo volverán a mover de sitio.

Sobre la 'P' de las carpetas: sí, 'P' viene de 'Proyecto', o sea, los enviados por el Gobierno al Congreso. Perdona por no dejarlo más claro. Y los que no tienen 'P' son los presupuestos aprobados por el Congreso. El presupuesto aprobado no deja de ser un presupuesto orientativo, así que no refleja el gasto real a final de año: eso sería la ejecución / liquidación, que no está disponible con el mismo detalle / formato, llevamos tiempo luchando para conseguir esa información y poder añadirla a la web.

**Comment by llrs** [comment]
Gracias por aclarármelo. Confiemos que pronto se pueda disponer de los gastos reales de forma accesible.
