### ISSUE TITLE
Las tablas de datos han cambiado el formato

### ISSUE THREAD

**Issue by dcabo** [civio/scraper-pge#5]
Los PGE 2021 están a punto de salir. Mirando los PGE de 2019 y 2020 publicados en [la web de la SEPG](https://www.sepg.pap.hacienda.gob.es/sitios/sepg/es-ES/Presupuestos/PGE/PGE2019Prorroga/Paginas/PGE2019Prorroga.aspx), he visto que han cambiado el formato completamente: los datos ya no se muestran usando `table`, sino `div`s a cascoporro, y con los clásicos estilos CSS aleatorios. Ver para creer.

<img width="918" alt="Screenshot 2020-10-28 at 01 15 13" src="https://user-images.githubusercontent.com/17741/97375464-2d20b000-18bb-11eb-95d4-ff1979364755.png">

Como ejemplo, la misma página [en 2018](https://www.sepg.pap.hacienda.gob.es/Presup/PGE2018Ley/MaestroDocumentos/PGE-ROM/doc/HTM/N_18_E_R_31_101_1_1_1_1911M_2.HTM) y [en 2020](https://www.sepg.pap.hacienda.gob.es/Presup/PGE2019Prorroga/MaestroDocumentos/PGE-ROM/doc/HTM/N_19P_E_R_31_101_1_1_1_1911M_2.HTM).

**Comment by EvaBelmonte** [comment]
¿Cómo de chungo es esto? en términos de trabajo para ti, me refiero

**Comment by dcabo** [comment]
Ayer en 2-3 horas apañé, creo, la Serie Roja. No pude mirar el resto porque en las prórrogas no existían las otras partes, pero calculo que en un par de horas debería tenerlo, una vez publiquen el PGE 2021 completo, que estoy a la espera.

**Comment by dcabo** [comment]
Hemos añadido código adicional para leer los datos de una nube de `div`s, manteniendo el existente para tablas. Lo bueno es que los cuatro tipos de ficheros que parseamos tienen la misma estructura, así que el código es el mismo. Lo malo, que el código es el mismo. Es decir, habría idealmente que refactorizar esto un poco, porque el código cada año incorpora una capa adicional de excepciones y rarezas, porque siempre siempre tocan algo. Pero es difícil ponerse a refactorizar algo que es muy enrevesado y que solo tocas una vez al año, así que de momento así se queda.
